
services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

  frontend:
    image: f1-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    
    ports:
      - 8000:80
    container_name: f1-frontend

  server:
    image: f1-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/.:/usr/src/app/

    ports:
      - 4000:4000
    container_name: f1-backend